#!/bin/sh

# =========
# Autostart
# =========
# Start keyboard
sxhkd &

# Start mouse
xsetroot -cursor_name left_ptr &

# Start status bar
bash /home/enindu/.config/polybar/launch.sh &

# Start wallpaper
feh --bg-fill /home/enindu/Pictures/Picture\ 9.jpg &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# ==========
# Workspaces
# ==========
bspc monitor -d Main Code Web Graphic Message Media

# =====
# Tiled
# =====
# Border width
bspc config border_width 0

# Gap between windows
bspc config window_gap 10

# Windows split ratio
bspc config split_ratio 0.5

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle false
