#!/bin/sh
# =========
# Autostart
# =========
# Start keybindings
sxhkd &

# Start compositor
picom &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start mouse
xsetroot -cursor_name left_ptr &

# Set wallpaper
feh --bg-fill /home/enindu/Pictures/Picture\ 9.jpg &

# Start status bar
bash /home/enindu/.config/polybar/launch.sh &

# ==========
# Workspaces
# ==========
bspc monitor -d Main Code Web Graphic Media Game

# =====
# Tiled
# =====
# Border width
bspc config border_width 0

# Gap between windows
bspc config window_gap 20

# Windows split ratio
bspc config split_ratio 0.5

# =======
# Monocle
# =======
# Borders
bspc config borderless_monocle false

# Gap
bspc config gapless_monocle false

# ============
# Window Rules
# ============
bspc rule -a code-oss         desktop="^2"
bspc rule -a Evolution        desktop="^3"
bspc rule -a firefox          desktop="^3"
bspc rule -a Chromium         desktop="^3"
bspc rule -a telegram-desktop desktop="^3"
bspc rule -a TelegramDesktop  desktop="^3"
bspc rule -a "Tor Browser"    desktop="^3"
bspc rule -a slack            desktop="^3"
bspc rule -a Slack            desktop="^3"
bspc rule -a filezilla        desktop="^3"
bspc rule -a Filezilla        desktop="^3"
bspc rule -a Darktable        desktop="^4"
bspc rule -a Gimp             desktop="^4"
bspc rule -a gimp             desktop="^4"
bspc rule -a Inkscape         desktop="^4"
